export const todosConstants = {
  GET_ALL: "GET_ALL",
  ADD_ONE: "ADD_ONE",
  EDIT_ONE: "EDIT_ONE",
  DELETE_ONE: "DELETE_ONE",
  DONE_ONE: "DONE_ONE",
  POSTPONE_ONE: "POSTPONE_ONE",
  DELETE_ALL: "DELETE_ALL",
  DELETE_ALL_NOT_IN_PROGRESS: "DELETE_ALL_NOT_DONE",
};

export const adviceConstants = {
  //   FETCH_ADVICE_REQUEST: "FETCH_ADVICE_REQUEST",
  //   FETCH_ADVICE_SUCCESS: "FETCH_ADVICE_SUCCESS",
  //   FETCH_ADVICE_FAILURE: "FETCH_ADVICE_FAILURE",
  GET_ONE: "GET_ONE",
  DELETE_ONE: "DELETE_ONE",
};
