export const todosConstants = {
  GET_ALL: "GET_ALL",
  ADD_ONE: "ADD_ONE",
  EDIT_ONE: "EDIT_ONE",
  DELETE_ONE: "DELETE_ONE",
  DONE_ONE: "DONE_ONE",
  POSTPONE_ONE: "POSTPONE_ONE",
  DELETE_ALL: "DELETE_ALL",
  DELETE_ALL_NOT_IN_PROGRESS: "DELETE_ALL_NOT_DONE",
};

export const currentAdviceConstants = {
  GET_CURRENT_ADVICE: "GET_CURRENT_ADVICE",
};

export const adviceConstants = {
  GET_ALL_ADVICE: "GET_ALL_ADVICE",
  ADD_ADVICE: "ADD_ADVICE",
  DELETE_ADVICE: "DELETE_ADVICE",
};
